### ISSUE TITLE
Pretender 0.3 causes rails app to crash

### ISSUE THREAD

**Issue by Littlejd1997** [ankane/pretender#19]
I wish I could provide more information as to what the issue is, but after updating our gems, our app stopped worked. Downgrading pretender back to 0.2 fixed the issue. The only error logged is as follows
     
     F, [2017-06-14T14:29:44.599534 #15416] FATAL -- : [55a6371f-bce8-4f0c-9346-901a223612a3]
     F, [2017-06-14T14:29:44.599708 #15416] FATAL -- : [55a6371f-bce8-4f0c-9346-901a223612a3] SystemStackError (stack level too deep):
     F, [2017-06-14T14:29:44.599805 #15416] FATAL -- : [55a6371f-bce8-4f0c-9346-901a223612a3]
     F, [2017-06-14T14:29:44.599892 #15416] FATAL -- : [55a6371f-bce8-4f0c-9346-901a223612a3] app/controllers/application_controller.rb:27:in `block in <class:ApplicationController>'

The line referenced if a very simple current_user if

     if current_user && current_user.is_admin

**Comment by ankane** [comment]
Hey @Littlejd1997, thanks for reporting 👍  A few questions:

1. What version of Rails are you on?
2. What authentication framework and version are you on?
3. Where is the `impersonates` method (`ApplicationController` or somewhere else)?

**Comment by Littlejd1997** [comment]
Rails 5.0.3
Devise 4.3.0 (also using Simple Token Authentication)
ApplicationController

**Comment by ankane** [comment]
Hey @Littlejd1997, I'm unable to reproduce the issue with those versions. It may be specific to your app. Let's see if anyone else reports this.

**Comment by Littlejd1997** [comment]
Ok thank you. If you have any other questions about my setup, let me know. If anything stands out for me I'll let you know

**Comment by cavneb** [comment]
I am running into this as well. Rails 5.0.2, Devise 4.3.0, App controller

**Comment by ankane** [comment]
I pushed a `stack_error_debug` branch. Would be great if one of you could try it and let me know if:

1. It fixes it
2. What it outputs (logs will be tagged with `[PRETENDER]`).

**Comment by cavneb** [comment]
@ankane It did not fix it:

```[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
[PRETENDER] ApplicationController
Completed 500 Internal Server Error in 38ms (ActiveRecord: 3.4ms)


stack level too deep excluded from capture: Not configured to send/capture in environment 'development'

SystemStackError (stack level too deep):

app/controllers/application_controller.rb:40:in `ensure_current_user'```

Error occurs when I call the method `true_user`

**Comment by ankane** [comment]
Thanks @cavneb. Try master. Should be fixed with 5b8682262a8eea1aa347adfce5f3c52c984592b9.

**Comment by samstickland** [comment]
Same problem here. Problem was resolved on master 👍

**Comment by ankane** [comment]
Thanks @samstickland 👍  I pushed out version 0.3.1.

**Comment by viniciuscacd** [comment]
Im still getting this error.

**Comment by ThomasBush** [comment]
Posting in case some one else makes the same mistake I did and finds this thread.

You will also get this error if you accidentally included the `impersonates :user` in more than one controller.  

This yields stack too deep error.  The documentation is clear: just add to the app controller, merely a mistake on my end.  Removing from other controllers resolved the issue.  Hopefully this helps someone else!
